title: Dristanta Silwal
description: CV
baseurl: ""
url: https://piazzai.github.io/cvless

theme: cvless

# site settings
taglong: online CV
tagshort: CV

# author settings
author:
  name: Dristanta Silwal
  email: dristantasilwal003@gmail.com
photo: assets/files/photo.jpg
address: Moscow, Idaho
phone: +1 512 956 1935

# social media links
social:
  facebook: dristanta.silwal
  github: dristanta-silwal
  instagram: silwal_dris
  linkedin: dristantasilwal
  stackoverflow: 20097636/dristanta-silwal
  x: Dristanta

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
